# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('file_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=400, verbose_name='file name')),
                ('content_sha1', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name': 'B2 file Upload',
                'verbose_name_plural': 'B2 file Uploads',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fileupload',
            unique_together=set([('file_id', 'name')]),
        ),
    ]
