# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='Tamaño en bytes'),
        ),
    ]
